# SPDX-FileCopyrightText: gb-dispatch-model contributors#
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# See https://snakemake.readthedocs.io/en/stable/executing/cli.html#profiles

logger: pypsa
cores: 1
storage-http-max-requests-per-second: 2
keep-storage-local-copies: true
